### PR TITLE
fix(version): fix versioning and organise imports

### PR DESCRIPTION
**Pull request by csatib02**
## 🚀 Changes Overview

- Fixed issue with versioning during build.
- Organised imports

### CODE REVIEW

**Review by Envoy49 — APPROVED** [review]
Thanks a lot

**Comment by Envoy49** [comment]
Hey, just a question.
After I merged this PR I don't see release number published with artifacts.
Not sure what is wrong, as it doesn't seem to be something to this PR.
Previous PR of yours which I merged successfully created a release version and artifacts.

**Comment by csatib02** [comment]
Hello,
I had a few ideas for your issue, but I might just ended up introducing a small bug. :D
Is there a platform I may contact you, Discord, Slack, etc, so we can handle this issue more easily.

**Comment by Envoy49** [comment]
@csatib02 I have got a discord account under `envoy49` nickname.
can you find me there?

**Comment by Envoy49** [comment]
@csatib02 looks like I fixed it

**Pull request merged**
